package com.ayprojects.helpinghands.api.enums;

public enum ContentType {
    CONTENT_PLACE, CONTENT_PROMOTION, CONTENT_REQUIREMENT,
    CONTENT_HH_POST, CONTENT_HH_POST_HELP,
    CONTENT_ADD_HH_POST_COMMENT,CONTENT_REMOVE_HH_POST_COMMENT,CONTENT_HELPING_HANDS
}
