package com.ayprojects.helpinghands.api.enums;

public enum  PlaceStepEnums {
    PLACE_DETAILS,
    NATURE_OF_BUSINESS,
    PLACE_AVAILAIBILITY,
    PRODUCTS,
    SINGLE_PRODUCT,
    PLACE_IMAGES,
    PRODUCT_PRICES_VISIBILITY,
    CURRENT_AVAILABLE_STATUS,
    REQUEST_TO_SHOW_PRODUCT_PRICES,
    CONFIRM_SHOW_PRODUCT_PRICE_REQUEST,
    REJECT_SHOW_PRODUCT_PRICE_REQUEST
}
